# agent token. Required.
apiToken: ""
clusterMonitoring:
  # Enable or disable cluster monitoring
  enabled: true
  # Global config for cluster monitoring agent
  config: {}
  # Resources for cluster monitoring agent daemonset
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 256Mi
  # Tolerations for cluster monitoring agent daemonset
  tolerations:
    - operator: Exists
remoteMonitoring:
  # Enable or disable remote monitoring
  enabled: false
  # Global config for remote monitoring agent
  config: {}
  # List of remote monitoring instances
  # Each instance spawns separate statefulset with agent, thus will appear as separate host in UI
  instances:
    # name of the instance (suffix of the statefulset name)
    default:
      ## Arbitary parent host name. If not defined, then defaults to statefulset hostname, e.g. 'op-agent-remote-monitoring-default-0'
      #hostname: remote-databases
      configs:
      #  my-postgres.yaml:
      #    plugin: postgresql
      #    config:
      #      host: db_ip           # (required) replace with your remote DB instance or cluster endpoint
      #      port: db_port         # (optional) uncomment and replace with your remote DB instance port if it's non-standard
      #      user: db_user         # (required) replace with your remote DB instance monitoring user
      #      password: db_password # (required) replace with your remote DB instance monitoring user's password.
      #      database: mydb        # (optional) replace with the database name you used to connect to when you created the okmeter schema, user, and function in PostgreSQL, if different from "postgres"
      #  my-redis.yaml:
      #    plugin: redis
      #    config:
      #      host: db_ip           # (required) replace with your remote DB instance or cluster endpoint
      #      port: db_port         # (optional) uncomment and replace with your remote DB instance port if it's non-standard
      #      password: db_password # (optional) uncomment and replace with your remote DB instance monitoring user's password.
  # Resources for remote monitoring agent statefulset
  resources:
    requests:
      memory: 512Mi
      cpu: 100m
    limits:
      memory: 512Mi
  # Persistent volume for remote monitoring agent statefulset
  persistentVolume:
    enabled: false
    size: 1Gi
    storageClass: ""
  # Node selector for remote monitoring agent statefulset
  nodeSelector: {}
  # Tolerations for remote monitoring agent statefulset
  tolerations:
    - operator: Exists
agent:
  productName: okagent
  image: registry.odarix.com/agent/odarix:latest
  baseDomain: odarix.com
  updateDomain: https://update.odarix.com
  collectorHost: dc3.okmeter.io
  collectorTlsHost: dc3.okmeter.io
  collectorPort: "443"
