{{- if .Values.remoteMonitoring.enabled }}
{{- range $instance, $params := .Values.remoteMonitoring.instances }}
{{- $_ := required (printf "Incomplete instance config. Please check .Values.remoteMonitoring.instances.%s" $instance) $params }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-remote-monitoring-%s" $.Chart.Name $instance }}
data:
{{- range $file, $data := required (printf "Incomplete instance config. You have to define at least one remote monitoring configuration at .Values.remoteMonitoring.instances.%s.configs" $instance) $params.configs }}
  {{ $file }}: {{ $data | toYaml | b64enc }}
{{- end }}
{{- end }}
{{- end }}